source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-archives'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'execjs'
gem 'therubyracer'
gem 'github-pages'
gem 'rouge'